//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumMeetEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildCondition
    {
        public int ChildConditionID { get; set; }
        public int ConditionID { get; set; }
        public int ChildID { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Condition Condition { get; set; }
    }
}
