//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumMeetEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Child()
        {
            this.ChildConditions = new HashSet<ChildCondition>();
            this.ParentChilds = new HashSet<ParentChild>();
        }
    
        public int ChildID { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public bool Verbal { get; set; }
        public string Description { get; set; }
        public int LevelID { get; set; }
    
        public virtual SupportLevel SupportLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildCondition> ChildConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentChild> ParentChilds { get; set; }

       
    }
}
