//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumMeetEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Message1 = new HashSet<Message>();
        }
    
        public int MessageID { get; set; }
        public int GroupID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime PostedDate { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> ParentMessageID { get; set; }
        public bool MessageReadStatus { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual Message Message2 { get; set; }
        public virtual User User { get; set; }
    }
}
